site_name: Sea
site_author: Callebe Gomes, callebedrums@gmail.com
site_description: SeaORM, SeaModel, Sea Framework, REST Service, ORM REST Service
repo_url: https://github.com/callebedrums/sea
theme: 'flatly'
pages:
- [index.md, Home]
- [model.md, Model]
- [configuration.md, Configuration]
- [about.md, About]
